Vagrant.configure("2") do |config|
  # Box que será utilizada
  config.vm.box = "gusztavvargadr/sql-server"

  # Configuração de rede privada com IP fixo
  config.vm.network "private_network", ip: "192.168.33.10"

  # Desativar a sincronização de pastas
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Configurações específicas para VirtualBox
  config.vm.provider "virtualbox" do |v|
    v.memory = "2048"  # Memória RAM alocada (em MB)
    v.cpus = 2         # Número de CPUs alocadas
  end
end
