Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/sql-server"
  config.vm.box_version = "2019.2102.2409"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provider "hyperv" do |vb|
	vb.gui = true
	vb.memory = "2048"
  end
end