Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/sql-server"

  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "hyperv"

  config.vm.provider "hyperv" do |h|
    h.memory = "2048"
    h.enable_virtualization_extensions = true
    h.linked_clone = true
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = "2048"
  end
end